### ISSUE TITLE
Fix blue box on click

### ISSUE THREAD

**Issue by nwaywood** [nwaywood/react-material-table#3]
atm when you click on a row, the accessibility blue box shows around the row to indicate that its focused. However, this blue box should only show when its tabbed to, not when its clicked

**Comment by AntTargett** [comment]
I think to resolve this issue instead of making the table headers have a tabIndex when actionable, instead render them as buttons to more accurately convey that they are actionable. 
Also should add styling to the button to display if it is the currently selected column

**Comment by AntTargett** [comment]
I think to resolve this issue instead of making the table headers have a tabIndex when actionable, instead render them as buttons to more accurately convey that they are actionable. 
Also should add styling to the button to display if it is the currently selected column

**Comment by AntTargett** [comment]
Updated header cells to use the colour of the text as the outline . 
Some focus styling is required for accessibility
Feel free to change it to something prettier. 
Did the same thing for the table rows

**Comment by AntTargett** [comment]
@nwaywood

**Comment by AntTargett** [comment]
Fix table div rows a8047dc5b42ce46729d41c9da31963fd2cd8dc9b
Fix table header cells 7ece6f5dd72a6ae94722840fa3fe8c1c11450fcd
