### ISSUE TITLE
[Question] sortCallback prop

### ISSUE THREAD

**Issue by charjac** [nwaywood/react-material-table#7]
Hi,
I am not able to make the table work with sortCallback prop.
Is it supposed to work ?
if it is, could you provide a dead simple example please ?

thanks
(great library by the way, it fit exactly my needs)

**Comment by AntTargett** [comment]
Hey Charjac
Are you intending to use the table for remote sorting? 
I will verify if the prop is working as intended but the intent of that prop is that it will override the local sorting and will provide all the information required in the callback to remote sort the table. 
An example is most definitely needed as well as better documentation for that prop. 
Will reply again here once the documentation has been updated 
Glad you like the table :)

**Comment by charjac** [comment]
actually even this doesn't log anything:
```jsx
  <Table
     columns={columns}
     data={data}
     sortCallback={console.log}
  />
```

**Comment by AntTargett** [comment]
Yep you are right 
Just checked the code, sortCallback isnt being called correctly 
Will fix in the next version 
Thanks for reporting!

**Comment by charjac** [comment]
you are welcome, thx for the answer

**Comment by AntTargett** [comment]
We just published the next version 
Version 0.0.6 will resolve this issue
Note that >=16.8.0 will also be required now (Not the alpha)
